import Head from "next/head";
import Navbar from "@/components/Header/Navbar";
import AboutUsBanner from "@/components/AboutUs/AboutUsBanner";
import PhotoGalleryMain from "@/components/PhotoGallery/PhotoGalleryMain";
import Footer from "@/components/Footer/Footer";

const PhotoGallery = () => {

    return (
        <>
            <Head>
                <title>Photo Gallery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <AboutUsBanner />
                <PhotoGalleryMain />
                <Footer />
            </main>
        </>
    );
}


export default PhotoGallery;