import Head from "next/head";
import Navbar from "@/components/Header/Navbar";
import AboutUsBanner from "@/components/AboutUs/AboutUsBanner";
import Footer from "@/components/Footer/Footer";

const BoardOfDirectors = () => {

    return (
        <>
            <Head>
                <title>Board Of Directors</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <AboutUsBanner />
                <Footer />
            </main>
        </>
    );
}


export default BoardOfDirectors;