import Head from "next/head";
import Navbar from "@/components/Header/Navbar";
import HomeBanner from "@/components/Home/HomeBanner/HomeBanner";
import Footer from "@/components/Footer/Footer";
import WelcomeHeraGroup from "@/components/Home/WelcomeHeraGroup/WelcomeHeraGroup";
import Newses from "@/components/News/Newses";


export default function Home() {
  return (
    <>
      <Head>
        <title>Hera Sweaters Ltd.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <HomeBanner />
        <WelcomeHeraGroup/>
        <Newses/>
        <Footer />
      </main>
    </>
  );
}
