import Head from "next/head";
import Navbar from "@/components/Header/Navbar";
import { Container } from "@mui/material";
import OverView from "@/components/AboutUs/Overview";
import OurMission from "@/components/AboutUs/OurMission";
import OurVision from "@/components/AboutUs/OurVision";
import OurSocial from "@/components/AboutUs/OurSocial";
import AboutUsBanner from "@/components/AboutUs/AboutUsBanner";
import Footer from "@/components/Footer/Footer";

const AboutUs = () => {

    return (
        <>
            <Head>
                <title>About US</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <AboutUsBanner />
                {/* <Container></Container> */}
                <OverView />
                <OurMission />
                <OurVision />
                <OurSocial />
                <Footer />
            </main>
        </>
    );
}


export default AboutUs;