import Head from "next/head";
import Link from "next/link";
import Navbar from "@/components/Header/Navbar";
import Newses from "@/components/News/Newses";
import Footer from "@/components/Footer/Footer";


const NewsBlogs = () => {
  return (
    <>
      <Head>
        <title>News Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Newses />
        <Footer />
        {/* {
          newsblogs.map((newsblog) => (
            <div key={newsblog.id}>
              <h1>{newsblog.title}</h1>
              <h2>{newsblog.content}</h2>
              <Link href={`/news/${newsblog.slug}`}>Details</Link>
            </div>
          ))
        } */}

        {/* <Link href='/news/blog'>Blog</Link> */}
      </main>
    </>
  );
}

// const newsblogs = [
//   {
//     id: 1,
//     slug: 'how-to-start-your-own-business',
//     title: 'How to Start Your Own Business',
//     author: 'John Doe',
//     date: '2024-10-01',
//     content: 'Learn the essential steps to successfully launch and manage your own business in today’s competitive market.'
//   },
//   {
//     id: 2,
//     slug: 'top-10-marketing-strategies',
//     title: 'Top 10 Marketing Strategies for 2024',
//     author: 'Jane Smith',
//     date: '2024-10-10',
//     content: 'Discover the top marketing strategies that can help you stay ahead in 2024, from social media to content marketing.'
//   },
//   {
//     id: 3,
//     slug: 'importance-of-work-life-balance',
//     title: 'The Importance of Work-Life Balance',
//     author: 'Emma Wilson',
//     date: '2024-09-15',
//     content: 'Explore why maintaining a healthy work-life balance is critical for productivity, health, and overall well-being.'
//   },
//   {
//     id: 4,
//     slug: 'beginner-guide-to-crypto',
//     title: 'A Beginner’s Guide to Cryptocurrency',
//     author: 'Liam Johnson',
//     date: '2024-08-20',
//     content: 'Understand the basics of cryptocurrency, blockchain technology, and how to safely get started with crypto investing.'
//   },
//   {
//     id: 5,
//     slug: 'eco-friendly-business-practices',
//     title: 'Eco-Friendly Business Practices for Sustainability',
//     author: 'Olivia Brown',
//     date: '2024-07-30',
//     content: 'Learn about eco-friendly practices you can implement to make your business more sustainable and environmentally responsible.'
//   }
// ];


export default NewsBlogs;